/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CambiarClaveRouteImport } from './routes/cambiar-clave'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConciliacionRouteImport } from './routes/conciliacion'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as GastosEmpresaRouteImport } from './routes/gastos-empresa'
import { Route as ImportacionesRouteImport } from './routes/importaciones'
import { Route as ImpuestosRouteImport } from './routes/impuestos'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as PresupuestosRouteImport } from './routes/presupuestos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as RendicionesRouteImport } from './routes/rendiciones'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ServicioTecnicoRouteImport } from './routes/servicio-tecnico'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ImportacionesCosteosRouteImport } from './routes/importaciones.costeos'
import { Route as ImportacionesEmbarquesRouteImport } from './routes/importaciones.embarques'
import { Route as ReportesFinancierosRouteImport } from './routes/reportes.financieros'
import { Route as ReportesOperativosRouteImport } from './routes/reportes.operativos'
import { Route as ReportesWorkflowRouteImport } from './routes/reportes.workflow'
import { Route as ServicioTecnicoBaseInstaladaRouteImport } from './routes/servicio-tecnico.base-instalada'
import { Route as ServicioTecnicoCatalogoRouteImport } from './routes/servicio-tecnico.catalogo'
import { Route as ServicioTecnicoContratosRouteImport } from './routes/servicio-tecnico.contratos'
import { Route as ServicioTecnicoOrdenesRouteImport } from './routes/servicio-tecnico.ordenes'
import { Route as ServicioTecnicoPlantillasRouteImport } from './routes/servicio-tecnico.plantillas'
import { Route as ServicioTecnicoProtocolosRouteImport } from './routes/servicio-tecnico.protocolos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarClaveRoute = CambiarClaveRouteImport.update({
  id: '/cambiar-clave',
  path: '/cambiar-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacionRoute = ConciliacionRouteImport.update({
  id: '/conciliacion',
  path: '/conciliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosEmpresaRoute = GastosEmpresaRouteImport.update({
  id: '/gastos-empresa',
  path: '/gastos-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacionesRoute = ImportacionesRouteImport.update({
  id: '/importaciones',
  path: '/importaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpuestosRoute = ImpuestosRouteImport.update({
  id: '/impuestos',
  path: '/impuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosRoute = PresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const RendicionesRoute = RendicionesRouteImport.update({
  id: '/rendiciones',
  path: '/rendiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicioTecnicoRoute = ServicioTecnicoRouteImport.update({
  id: '/servicio-tecnico',
  path: '/servicio-tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacionesCosteosRoute = ImportacionesCosteosRouteImport.update({
  id: '/costeos',
  path: '/costeos',
  getParentRoute: () => ImportacionesRoute,
} as any)
const ImportacionesEmbarquesRoute = ImportacionesEmbarquesRouteImport.update({
  id: '/embarques',
  path: '/embarques',
  getParentRoute: () => ImportacionesRoute,
} as any)
const ReportesFinancierosRoute = ReportesFinancierosRouteImport.update({
  id: '/financieros',
  path: '/financieros',
  getParentRoute: () => ReportesRoute,
} as any)
const ReportesOperativosRoute = ReportesOperativosRouteImport.update({
  id: '/operativos',
  path: '/operativos',
  getParentRoute: () => ReportesRoute,
} as any)
const ReportesWorkflowRoute = ReportesWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => ReportesRoute,
} as any)
const ServicioTecnicoBaseInstaladaRoute =
  ServicioTecnicoBaseInstaladaRouteImport.update({
    id: '/base-instalada',
    path: '/base-instalada',
    getParentRoute: () => ServicioTecnicoRoute,
  } as any)
const ServicioTecnicoCatalogoRoute = ServicioTecnicoCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => ServicioTecnicoRoute,
} as any)
const ServicioTecnicoContratosRoute =
  ServicioTecnicoContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => ServicioTecnicoRoute,
  } as any)
const ServicioTecnicoOrdenesRoute = ServicioTecnicoOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => ServicioTecnicoRoute,
} as any)
const ServicioTecnicoPlantillasRoute =
  ServicioTecnicoPlantillasRouteImport.update({
    id: '/plantillas',
    path: '/plantillas',
    getParentRoute: () => ServicioTecnicoRoute,
  } as any)
const ServicioTecnicoProtocolosRoute =
  ServicioTecnicoProtocolosRouteImport.update({
    id: '/protocolos',
    path: '/protocolos',
    getParentRoute: () => ServicioTecnicoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/cambiar-clave': typeof CambiarClaveRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/gastos-empresa': typeof GastosEmpresaRoute
  '/importaciones': typeof ImportacionesRouteWithChildren
  '/impuestos': typeof ImpuestosRoute
  '/inventario': typeof InventarioRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/servicio-tecnico': typeof ServicioTecnicoRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/importaciones/costeos': typeof ImportacionesCosteosRoute
  '/importaciones/embarques': typeof ImportacionesEmbarquesRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
  '/servicio-tecnico/base-instalada': typeof ServicioTecnicoBaseInstaladaRoute
  '/servicio-tecnico/catalogo': typeof ServicioTecnicoCatalogoRoute
  '/servicio-tecnico/contratos': typeof ServicioTecnicoContratosRoute
  '/servicio-tecnico/ordenes': typeof ServicioTecnicoOrdenesRoute
  '/servicio-tecnico/plantillas': typeof ServicioTecnicoPlantillasRoute
  '/servicio-tecnico/protocolos': typeof ServicioTecnicoProtocolosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/cambiar-clave': typeof CambiarClaveRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/gastos-empresa': typeof GastosEmpresaRoute
  '/importaciones': typeof ImportacionesRouteWithChildren
  '/impuestos': typeof ImpuestosRoute
  '/inventario': typeof InventarioRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/servicio-tecnico': typeof ServicioTecnicoRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/importaciones/costeos': typeof ImportacionesCosteosRoute
  '/importaciones/embarques': typeof ImportacionesEmbarquesRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
  '/servicio-tecnico/base-instalada': typeof ServicioTecnicoBaseInstaladaRoute
  '/servicio-tecnico/catalogo': typeof ServicioTecnicoCatalogoRoute
  '/servicio-tecnico/contratos': typeof ServicioTecnicoContratosRoute
  '/servicio-tecnico/ordenes': typeof ServicioTecnicoOrdenesRoute
  '/servicio-tecnico/plantillas': typeof ServicioTecnicoPlantillasRoute
  '/servicio-tecnico/protocolos': typeof ServicioTecnicoProtocolosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/cambiar-clave': typeof CambiarClaveRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/gastos-empresa': typeof GastosEmpresaRoute
  '/importaciones': typeof ImportacionesRouteWithChildren
  '/impuestos': typeof ImpuestosRoute
  '/inventario': typeof InventarioRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/servicio-tecnico': typeof ServicioTecnicoRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/importaciones/costeos': typeof ImportacionesCosteosRoute
  '/importaciones/embarques': typeof ImportacionesEmbarquesRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
  '/servicio-tecnico/base-instalada': typeof ServicioTecnicoBaseInstaladaRoute
  '/servicio-tecnico/catalogo': typeof ServicioTecnicoCatalogoRoute
  '/servicio-tecnico/contratos': typeof ServicioTecnicoContratosRoute
  '/servicio-tecnico/ordenes': typeof ServicioTecnicoOrdenesRoute
  '/servicio-tecnico/plantillas': typeof ServicioTecnicoPlantillasRoute
  '/servicio-tecnico/protocolos': typeof ServicioTecnicoProtocolosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/auth'
    | '/cambiar-clave'
    | '/catalogo'
    | '/clientes'
    | '/conciliacion'
    | '/configuracion'
    | '/contabilidad'
    | '/cotizaciones'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/gastos-empresa'
    | '/importaciones'
    | '/impuestos'
    | '/inventario'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/servicio-tecnico'
    | '/workflow'
    | '/importaciones/costeos'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
    | '/servicio-tecnico/base-instalada'
    | '/servicio-tecnico/catalogo'
    | '/servicio-tecnico/contratos'
    | '/servicio-tecnico/ordenes'
    | '/servicio-tecnico/plantillas'
    | '/servicio-tecnico/protocolos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/auth'
    | '/cambiar-clave'
    | '/catalogo'
    | '/clientes'
    | '/conciliacion'
    | '/configuracion'
    | '/contabilidad'
    | '/cotizaciones'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/gastos-empresa'
    | '/importaciones'
    | '/impuestos'
    | '/inventario'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/servicio-tecnico'
    | '/workflow'
    | '/importaciones/costeos'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
    | '/servicio-tecnico/base-instalada'
    | '/servicio-tecnico/catalogo'
    | '/servicio-tecnico/contratos'
    | '/servicio-tecnico/ordenes'
    | '/servicio-tecnico/plantillas'
    | '/servicio-tecnico/protocolos'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/auth'
    | '/cambiar-clave'
    | '/catalogo'
    | '/clientes'
    | '/conciliacion'
    | '/configuracion'
    | '/contabilidad'
    | '/cotizaciones'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/gastos-empresa'
    | '/importaciones'
    | '/impuestos'
    | '/inventario'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/servicio-tecnico'
    | '/workflow'
    | '/importaciones/costeos'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
    | '/servicio-tecnico/base-instalada'
    | '/servicio-tecnico/catalogo'
    | '/servicio-tecnico/contratos'
    | '/servicio-tecnico/ordenes'
    | '/servicio-tecnico/plantillas'
    | '/servicio-tecnico/protocolos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRoute: typeof AdministracionRoute
  AuthRoute: typeof AuthRoute
  CambiarClaveRoute: typeof CambiarClaveRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  ConciliacionRoute: typeof ConciliacionRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ContabilidadRoute: typeof ContabilidadRoute
  CotizacionesRoute: typeof CotizacionesRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  FacturasRoute: typeof FacturasRoute
  GastosRoute: typeof GastosRoute
  GastosEmpresaRoute: typeof GastosEmpresaRoute
  ImportacionesRoute: typeof ImportacionesRouteWithChildren
  ImpuestosRoute: typeof ImpuestosRoute
  InventarioRoute: typeof InventarioRoute
  PresupuestosRoute: typeof PresupuestosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ProyectosRoute: typeof ProyectosRoute
  RendicionesRoute: typeof RendicionesRoute
  ReportesRoute: typeof ReportesRouteWithChildren
  ServicioTecnicoRoute: typeof ServicioTecnicoRouteWithChildren
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-clave': {
      id: '/cambiar-clave'
      path: '/cambiar-clave'
      fullPath: '/cambiar-clave'
      preLoaderRoute: typeof CambiarClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacion': {
      id: '/conciliacion'
      path: '/conciliacion'
      fullPath: '/conciliacion'
      preLoaderRoute: typeof ConciliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-empresa': {
      id: '/gastos-empresa'
      path: '/gastos-empresa'
      fullPath: '/gastos-empresa'
      preLoaderRoute: typeof GastosEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importaciones': {
      id: '/importaciones'
      path: '/importaciones'
      fullPath: '/importaciones'
      preLoaderRoute: typeof ImportacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impuestos': {
      id: '/impuestos'
      path: '/impuestos'
      fullPath: '/impuestos'
      preLoaderRoute: typeof ImpuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos': {
      id: '/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof PresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendiciones': {
      id: '/rendiciones'
      path: '/rendiciones'
      fullPath: '/rendiciones'
      preLoaderRoute: typeof RendicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicio-tecnico': {
      id: '/servicio-tecnico'
      path: '/servicio-tecnico'
      fullPath: '/servicio-tecnico'
      preLoaderRoute: typeof ServicioTecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importaciones/costeos': {
      id: '/importaciones/costeos'
      path: '/costeos'
      fullPath: '/importaciones/costeos'
      preLoaderRoute: typeof ImportacionesCosteosRouteImport
      parentRoute: typeof ImportacionesRoute
    }
    '/importaciones/embarques': {
      id: '/importaciones/embarques'
      path: '/embarques'
      fullPath: '/importaciones/embarques'
      preLoaderRoute: typeof ImportacionesEmbarquesRouteImport
      parentRoute: typeof ImportacionesRoute
    }
    '/reportes/financieros': {
      id: '/reportes/financieros'
      path: '/financieros'
      fullPath: '/reportes/financieros'
      preLoaderRoute: typeof ReportesFinancierosRouteImport
      parentRoute: typeof ReportesRoute
    }
    '/reportes/operativos': {
      id: '/reportes/operativos'
      path: '/operativos'
      fullPath: '/reportes/operativos'
      preLoaderRoute: typeof ReportesOperativosRouteImport
      parentRoute: typeof ReportesRoute
    }
    '/reportes/workflow': {
      id: '/reportes/workflow'
      path: '/workflow'
      fullPath: '/reportes/workflow'
      preLoaderRoute: typeof ReportesWorkflowRouteImport
      parentRoute: typeof ReportesRoute
    }
    '/servicio-tecnico/base-instalada': {
      id: '/servicio-tecnico/base-instalada'
      path: '/base-instalada'
      fullPath: '/servicio-tecnico/base-instalada'
      preLoaderRoute: typeof ServicioTecnicoBaseInstaladaRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
    '/servicio-tecnico/catalogo': {
      id: '/servicio-tecnico/catalogo'
      path: '/catalogo'
      fullPath: '/servicio-tecnico/catalogo'
      preLoaderRoute: typeof ServicioTecnicoCatalogoRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
    '/servicio-tecnico/contratos': {
      id: '/servicio-tecnico/contratos'
      path: '/contratos'
      fullPath: '/servicio-tecnico/contratos'
      preLoaderRoute: typeof ServicioTecnicoContratosRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
    '/servicio-tecnico/ordenes': {
      id: '/servicio-tecnico/ordenes'
      path: '/ordenes'
      fullPath: '/servicio-tecnico/ordenes'
      preLoaderRoute: typeof ServicioTecnicoOrdenesRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
    '/servicio-tecnico/plantillas': {
      id: '/servicio-tecnico/plantillas'
      path: '/plantillas'
      fullPath: '/servicio-tecnico/plantillas'
      preLoaderRoute: typeof ServicioTecnicoPlantillasRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
    '/servicio-tecnico/protocolos': {
      id: '/servicio-tecnico/protocolos'
      path: '/protocolos'
      fullPath: '/servicio-tecnico/protocolos'
      preLoaderRoute: typeof ServicioTecnicoProtocolosRouteImport
      parentRoute: typeof ServicioTecnicoRoute
    }
  }
}

interface ImportacionesRouteChildren {
  ImportacionesCosteosRoute: typeof ImportacionesCosteosRoute
  ImportacionesEmbarquesRoute: typeof ImportacionesEmbarquesRoute
}

const ImportacionesRouteChildren: ImportacionesRouteChildren = {
  ImportacionesCosteosRoute: ImportacionesCosteosRoute,
  ImportacionesEmbarquesRoute: ImportacionesEmbarquesRoute,
}

const ImportacionesRouteWithChildren = ImportacionesRoute._addFileChildren(
  ImportacionesRouteChildren,
)

interface ReportesRouteChildren {
  ReportesFinancierosRoute: typeof ReportesFinancierosRoute
  ReportesOperativosRoute: typeof ReportesOperativosRoute
  ReportesWorkflowRoute: typeof ReportesWorkflowRoute
}

const ReportesRouteChildren: ReportesRouteChildren = {
  ReportesFinancierosRoute: ReportesFinancierosRoute,
  ReportesOperativosRoute: ReportesOperativosRoute,
  ReportesWorkflowRoute: ReportesWorkflowRoute,
}

const ReportesRouteWithChildren = ReportesRoute._addFileChildren(
  ReportesRouteChildren,
)

interface ServicioTecnicoRouteChildren {
  ServicioTecnicoBaseInstaladaRoute: typeof ServicioTecnicoBaseInstaladaRoute
  ServicioTecnicoCatalogoRoute: typeof ServicioTecnicoCatalogoRoute
  ServicioTecnicoContratosRoute: typeof ServicioTecnicoContratosRoute
  ServicioTecnicoOrdenesRoute: typeof ServicioTecnicoOrdenesRoute
  ServicioTecnicoPlantillasRoute: typeof ServicioTecnicoPlantillasRoute
  ServicioTecnicoProtocolosRoute: typeof ServicioTecnicoProtocolosRoute
}

const ServicioTecnicoRouteChildren: ServicioTecnicoRouteChildren = {
  ServicioTecnicoBaseInstaladaRoute: ServicioTecnicoBaseInstaladaRoute,
  ServicioTecnicoCatalogoRoute: ServicioTecnicoCatalogoRoute,
  ServicioTecnicoContratosRoute: ServicioTecnicoContratosRoute,
  ServicioTecnicoOrdenesRoute: ServicioTecnicoOrdenesRoute,
  ServicioTecnicoPlantillasRoute: ServicioTecnicoPlantillasRoute,
  ServicioTecnicoProtocolosRoute: ServicioTecnicoProtocolosRoute,
}

const ServicioTecnicoRouteWithChildren = ServicioTecnicoRoute._addFileChildren(
  ServicioTecnicoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRoute: AdministracionRoute,
  AuthRoute: AuthRoute,
  CambiarClaveRoute: CambiarClaveRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  ConciliacionRoute: ConciliacionRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ContabilidadRoute: ContabilidadRoute,
  CotizacionesRoute: CotizacionesRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  FacturasRoute: FacturasRoute,
  GastosRoute: GastosRoute,
  GastosEmpresaRoute: GastosEmpresaRoute,
  ImportacionesRoute: ImportacionesRouteWithChildren,
  ImpuestosRoute: ImpuestosRoute,
  InventarioRoute: InventarioRoute,
  PresupuestosRoute: PresupuestosRoute,
  ProveedoresRoute: ProveedoresRoute,
  ProyectosRoute: ProyectosRoute,
  RendicionesRoute: RendicionesRoute,
  ReportesRoute: ReportesRouteWithChildren,
  ServicioTecnicoRoute: ServicioTecnicoRouteWithChildren,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
