/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RendicionesRouteImport } from './routes/rendiciones'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as PresupuestosRouteImport } from './routes/presupuestos'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportesWorkflowRouteImport } from './routes/reportes.workflow'
import { Route as ReportesOperativosRouteImport } from './routes/reportes.operativos'
import { Route as ReportesFinancierosRouteImport } from './routes/reportes.financieros'

const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RendicionesRoute = RendicionesRouteImport.update({
  id: '/rendiciones',
  path: '/rendiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosRoute = PresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesWorkflowRoute = ReportesWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => ReportesRoute,
} as any)
const ReportesOperativosRoute = ReportesOperativosRouteImport.update({
  id: '/operativos',
  path: '/operativos',
  getParentRoute: () => ReportesRoute,
} as any)
const ReportesFinancierosRoute = ReportesFinancierosRouteImport.update({
  id: '/financieros',
  path: '/financieros',
  getParentRoute: () => ReportesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/presupuestos': typeof PresupuestosRoute
  '/proveedores': typeof ProveedoresRoute
  '/proyectos': typeof ProyectosRoute
  '/rendiciones': typeof RendicionesRoute
  '/reportes': typeof ReportesRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/reportes/financieros': typeof ReportesFinancierosRoute
  '/reportes/operativos': typeof ReportesOperativosRoute
  '/reportes/workflow': typeof ReportesWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/auth'
    | '/clientes'
    | '/configuracion'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/workflow'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/auth'
    | '/clientes'
    | '/configuracion'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/workflow'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/auth'
    | '/clientes'
    | '/configuracion'
    | '/dashboard'
    | '/documentos'
    | '/facturas'
    | '/gastos'
    | '/presupuestos'
    | '/proveedores'
    | '/proyectos'
    | '/rendiciones'
    | '/reportes'
    | '/workflow'
    | '/reportes/financieros'
    | '/reportes/operativos'
    | '/reportes/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRoute: typeof AdministracionRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  FacturasRoute: typeof FacturasRoute
  GastosRoute: typeof GastosRoute
  PresupuestosRoute: typeof PresupuestosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ProyectosRoute: typeof ProyectosRoute
  RendicionesRoute: typeof RendicionesRoute
  ReportesRoute: typeof ReportesRouteWithChildren
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendiciones': {
      id: '/rendiciones'
      path: '/rendiciones'
      fullPath: '/rendiciones'
      preLoaderRoute: typeof RendicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos': {
      id: '/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof PresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/workflow': {
      id: '/reportes/workflow'
      path: '/workflow'
      fullPath: '/reportes/workflow'
      preLoaderRoute: typeof ReportesWorkflowRouteImport
      parentRoute: typeof ReportesRoute
    }
    '/reportes/operativos': {
      id: '/reportes/operativos'
      path: '/operativos'
      fullPath: '/reportes/operativos'
      preLoaderRoute: typeof ReportesOperativosRouteImport
      parentRoute: typeof ReportesRoute
    }
    '/reportes/financieros': {
      id: '/reportes/financieros'
      path: '/financieros'
      fullPath: '/reportes/financieros'
      preLoaderRoute: typeof ReportesFinancierosRouteImport
      parentRoute: typeof ReportesRoute
    }
  }
}

interface ReportesRouteChildren {
  ReportesFinancierosRoute: typeof ReportesFinancierosRoute
  ReportesOperativosRoute: typeof ReportesOperativosRoute
  ReportesWorkflowRoute: typeof ReportesWorkflowRoute
}

const ReportesRouteChildren: ReportesRouteChildren = {
  ReportesFinancierosRoute: ReportesFinancierosRoute,
  ReportesOperativosRoute: ReportesOperativosRoute,
  ReportesWorkflowRoute: ReportesWorkflowRoute,
}

const ReportesRouteWithChildren = ReportesRoute._addFileChildren(
  ReportesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRoute: AdministracionRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  FacturasRoute: FacturasRoute,
  GastosRoute: GastosRoute,
  PresupuestosRoute: PresupuestosRoute,
  ProveedoresRoute: ProveedoresRoute,
  ProyectosRoute: ProyectosRoute,
  RendicionesRoute: RendicionesRoute,
  ReportesRoute: ReportesRouteWithChildren,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
